$kind: http-request
name: Create Role
method: POST
url: '{{baseUrl}}/roles'
order: 1000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "companyId": "{{companyId}}",
      "name": "Sales Manager",
      "description": "Manages sales operations"
    }
